# Values to deploy datahub with the helm chart
# See: https://github.com/acryldata/datahub-helm

global:
  datahub_analytics_enabled: false
  datahub:
    appVersion: "1.0"
    gms:
      port: "8080"
  elasticsearch:
    # Secret
    host: ""
    port: "443"
    useSSL: true
    auth:
      # Secret
      username: ""
      password:
        secretRef: "datahub"
        secretKey: "es-password"
  kafka:
    bootstrap:
      # Secret
      server: ""
    schemaregistry:
      # Secret
      url: ""
  sql:
    datasource:
      # Secret
      host: ""
      # Secret
      hostForMysqlClient: ""
      # Secret
      url: ""
      # Secret
      username: ""
      password:
        secretRef: "datahub"
        secretKey: "mysql-password"
  graph_service_impl: "elasticsearch"
  springKafkaConfigurationOverrides:
    security.protocol: SASL_SSL
    kafkastore.security.protocol: SASL_SSL
    # Secret
    sasl.jaas.config: ""
    
    # Probably not needed
    sasl.mechanism: PLAIN
    sasl.username: ""
    sasl.password: ""

datahub-frontend:
  enabled: true
  image:
    repository: linkedin/datahub-frontend-react
    tag: "v0.8.6"
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi
  ingress:
    enabled: false
    hosts:
      # Secret
      - host: ""
        paths:
          - "/"

datahub-gms:
  enabled: true
  image:
    repository: linkedin/datahub-gms
    tag: "v0.8.6"
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi
  extraEnvs:
    # All Secret
    # Some of these are not needed, not clear which
    # See https://datahubproject.io/docs/how/kafka-config
    - name: METADATA_CHANGE_EVENT_NAME
      value: ""
    - name: METADATA_AUDIT_EVENT_NAME
      value: ""
    - name: FAILED_METADATA_CHANGE_EVENT_NAME
      value: ""
    - name: KAFKA_MCE_TOPIC_NAME
      value: ""
    - name: KAFKA_FMCE_TOPIC_NAME
      value: ""
    - name: KAFKA_TOPIC_NAME
      value: ""

    # TODO: GMS seems to ignore this one?
    - name: KAFKA_CONSUMER_GROUP_ID
      value: ""

datahub-ingestion-cron:
  enabled: false

elasticsearchSetupJob:
  enabled: true
  image:
    repository: linkedin/datahub-elasticsearch-setup
    tag: "v0.8.6"

kafkaSetupJob:
  enabled: false

mysqlSetupJob:
  enabled: true
  image:
    repository: acryldata/datahub-mysql-setup
    tag: "v0.8.6"

datahubUpgrade:
  enabled: false
  image:
    repository: acryldata/datahub-upgrade
    tag: "v0.8.6"
  noCodeDataMigration:
    sqlDbType: "MYSQL"
