apiVersion: v1
kind: Secret
metadata:
  name: datahub
type: Opaque
stringData:
  es-password: $(json.es_password.value)
  mysql-password: $(json.db_password.value)
  auth-oidc-client-secret: $(AUTH_OIDC_CLIENT_SECRET)
